### ISSUE TITLE
設定したアラームのON/OFFがわかりにくい

### ISSUE THREAD

**Issue by Oz-Soma** [enpitut/Friendly#13]
->黒くなっているのがON,中抜きがOFFだと思うけど初見でとまどった。

**Comment by Oz-Soma** [comment]
・文字でON/OFFを表示
・モノクロ表示とカラー表示で分ける
・コントラストとか明度彩度
とかだろうか

> iphoneのアラームだけど参考程度に
> ![2015-12-06 23 48 24](https://cloud.githubusercontent.com/assets/13823915/11613880/1af5aab6-9c74-11e5-9bff-0c5e77226e12.png)

**Comment by ghost** [comment]
文字で ON/OFF を表示するように変更しました。https://github.com/enpitut/Friendly/pull/31

モノクロ・カラーの切り替え等もしたほうがよいでしょうか。
