### ISSUE TITLE
アラーム音が鳴らない

### ISSUE THREAD

**Issue by Oz-Soma** [enpitut/Friendly#15]
設定した時間になってもアラーム音が鳴らない。

**Comment by Oz-Soma** [comment]
コードとかは見てないので確認できたらします

**Comment by ghost** [comment]
- アラームは ON になっていますか？（設定時間の横に ★ が表示されている状態のとき ON）
- 設定時間になると「AlarmNortificationActivity」画面に遷移しますか？

**Comment by Oz-Soma** [comment]
・アラームはON
・設定時間になると最初のグラフが描画してる画面に戻る。何かしらのイベントは発生してるのかな
確認なんだけどマージ済みだよね？

**Comment by ghost** [comment]
マージ済です。

ターミナルで、次のコマンドを実行してから、再度動作確認をしてみてください。
もしかしたら、最新のコードがローカルにコピーできていないのかも。
$ git checkout master
$ git pull

**Comment by Oz-Soma** [comment]
音確認しました
