### ISSUE TITLE
開発の継続が困難

### ISSUE THREAD

**Issue by mizutoki79** [enpitut/Friendly#17]
就寝判定について書いていましたが、開発の継続が困難なので代わりに開発してほしいです。
DBからtimestampを読み取って、smaller...2種類の条件をゆるくして、sleepCheckはtimestampを返すようにしてほしいです。
変数DBColumnに"timestamp"を加えればDBから読み取りは可能になると思います。
実機が無かったので実際のデータでの確認は行えていません、そのため読み取れない等のバグがあるかもしれません。
始めから作り直した方が良ければそれでもかまいません。
よろしくお願いします。
申し訳ございません。

**Comment by Oz-Soma** [comment]
引き継ぎます。わからないことがあったら聞くのでサポートお願いします。

**Comment by Oz-Soma** [comment]
Analyzeクラス以外ってアラーム実装前のコード？

**Comment by ghost** [comment]
MainActivity に呼び出す部分がある。
https://github.com/enpitut/Friendly/pull/16/files

**Comment by Oz-Soma** [comment]
忙しくなったので@mizutoki79に戻します。よろしくお願いします

**Comment by mizutoki79** [comment]
引き継ぎます

**Comment by mizutoki79** [comment]
明日の昼（12/8 12:00）までに以下の2点に着手し、マージできる状態にします。
- DBへの書き込みと実際に書き込まれた就寝時刻の検証
- 就寝判定で就寝時刻が取得できなかった場合の処理の追加

**Comment by mizutoki79** [comment]
すいません技術的な問題で時間に間に合いそうにありません。

**Comment by mizutoki79** [comment]
一緒に開発を進めてくれる人がほしいです。
実装の期限（11/29）をだいぶ過ぎているので、至急お願いします。

**Comment by mizutoki79** [comment]
就寝判定について、忙しくて昨日のコミット（6a0e29786111b5106918b410f062c56ef4d99a6c）から進んでいません。
研究のテーマ決めや他の授業の課題で時間がないため、明日もあまり時間がとれません。
自分は開発に携わりたいと思っていますが、期限までに開発が終わらなそうなので、誰か（できれば、そうま）と協力して実装をしたいです。
