### ISSUE TITLE
サービスの実装について

### ISSUE THREAD

**Issue by 15nm721f** [enpitut/Friendly#18]
申し訳無いですが，今日中だと厳しいと判断したため，サービスの実装の引き継ぎをお願いしたいです．
やってもらいたいことは，

・加速度取得モード起動時にサービスの開始
　serviceブランチに遡及時間を10時間として実装したものがあります．
　アラーム設定時間にサービスの起動は確認済みです．

・起床時（アラームSTOP時？）にサービス終了
　関数一つでできると思います．

・スリープを行っても加速度を取得出来ているかの確認
　これができていればサービスの実装は完了だと考えています．
　
現在のコードでどこにコードの追加をすればいいか，テストを確認するための操作などがわからないため，引き継ぎお願いします．

**Comment by ghost** [comment]
加速度取得処理のサービス化を実装しました。
https://github.com/enpitut/Friendly/commit/b51fc541ec2648fb2c8f46889094342ffa49e8b3
